package com;

enum EventType {
    FLIGHT_BOOKING,
    FLIGHT_PAYMENT_CONFIRMATION,
    HOTEL_BOOKING,
    HOTEL_PAYMENT_CONFIRMATION,
    CAR_RENTAL,
    CAR_RENTAL_PAYMENT_CONFIRMATION

}
